### ISSUE TITLE
/routing/v1/router_groups returns a 401 instead of 403 if user doesn't have the correct scope

### ISSUE THREAD

**Issue by forbushbl** [cloudfoundry/routing-api#14]
It appears that when listing router_groups, the routing-api is returning a 401 if the client doesn't have the correct scope ([router_groups_handler.go:43](https://github.com/cloudfoundry-incubator/routing-api/blob/c8d190ac4869b149b81430256362b209718cb793/handlers/router_groups_handler.go#L43)). This causes cf-java-client to think that the user token is bad (See [cf-java-client issue 826](https://github.com/cloudfoundry/cf-java-client/issues/826)). 

Ideally you would return a 401 wherever you encounter an invalid token and a 403 whenever you encounter a client that is missing the required scope.

**Comment by forbushbl** [comment]
So to provide a little bit of context around this issue, I was interacting with the routing api via the cf-java-client and discovered that the client hangs when creating a shared tcp domain in Cloud Foundry if the user doesn't have access to read the router groups. When I looked into the issue with them, it was discovered that the routing API is returning a 401 when the client doesn't have the correct scope to read the router groups. Currently, they don't have a way to work around this issue since they expect a 403 to tell them that they don't have access. For them a 401 means that they need to refresh their token.

The cf-java-client team has made some improvements but ultimately this is something that will probably need to be fixed in the routing API.

**Comment by shubhaat** [comment]
Hi @forbushbl , 

The routing team does not have the bandwidth currently to work on this. Would you be able to make a PR with this change? 

Regards, 
Shubha

**Comment by jeffpak** [comment]
Hi @forbushbl ,

Going to close this issue since we haven't heard back in over a year. If you still would like us to prioritize this, feel free to reopen this issue. Again, we are open to PR's, but still do not have the bandwidth to address this.
